### ISSUE TITLE
Markdown bullets not displaying

### ISSUE THREAD

**Issue by OJ423** [terminusdb/terminuscms#59]
Markdown bullet points do not display in the preview setting - 

![image](https://user-images.githubusercontent.com/88653154/217510883-df2657fe-b6cd-4569-a25f-b4177a062fd0.png)

**Comment by geoffwhittington** [comment]
Where is this Markdown capability on dashboard.terminusdb.com? I see String types supported as a property but I didn't know it supported formatting Markdown

**Comment by GavinMendelGleason** [comment]
We have a secret escape hatch that enables it at the minute, but will add it to the UI in the next few weeks. 

To enable, edit the schema, adding a `render_as` flag in `@metadata`: 

```json
 {
        "@id": "Body",
        "@metadata": {
            "render_as": {
                "value": "markdown"
            }
        },
        "@type": "Class",
        "value": "xsd:string"
    }
```

**Comment by geoffwhittington** [comment]
Amazing. Thanks!

**Comment by geoffwhittington** [comment]
So this works for a Document, not at the attribute level? Is it a best practice to model like this?

**Comment by GavinMendelGleason** [comment]
It is per attribute, with the `"render_as"` referring to a pair of `"attribute" : "render_type"`. We intend to make these selectable options in the interface, so it should be safe to proceed with it.  Ultimately it would be nice to have the interface directives coming from an entirely different data product, but I don't think that is in scope for the next year or more. So I guess it could be considered "best practice".

**Comment by geoffwhittington** [comment]
Ok cool - I guess where I have gone wrong is not being able to map your example to my JSON. In my JSON View my target SubDocument has three attibutes but only one `@id`. So I thought `@metadata` had to be applied to the Subdocument not at a specific attribute.

In this example I want to make the `description` render as Markdown.

```
    {
        "@id": "Intelligence",
        "@key": {
            "@type": "Random"
        },
        "@subdocument": [],
        "@type": "Class",
        "description": {
            "@class": "xsd:string",
            "@type": "Optional"
        },
        "id": {
            "@class": "xsd:string",
            "@type": "Optional"
        },
        "title": {
            "@class": "xsd:string",
            "@type": "Optional"
        }
    },
```

**Comment by GavinMendelGleason** [comment]
I believe the following should work: 
```json
 {
        "@id": "Intelligence",
        "@key": {
            "@type": "Random"
        },
        "@subdocument": [],
        "@type": "Class",
        "@metadata" : { "render_as" : { "description" : "markdown" } },
        "description": {
            "@class": "xsd:string",
            "@type": "Optional"
        },
        "id": {
            "@class": "xsd:string",
            "@type": "Optional"
        },
        "title": {
            "@class": "xsd:string",
            "@type": "Optional"
        }
}
```

**Comment by geoffwhittington** [comment]
Oh I get it now, thanks!

**Comment by OJ423** [comment]
Fixed before launch
