### ISSUE TITLE
Diffs disappear / Can't see Diffs when submitting a CR for an edited document

### ISSUE THREAD

**Issue by sreyac** [terminusdb/terminuscms#66]
I edited an existing page (in TerminusDB_docs) and submitted a CR for review ('Random Test' page). When reviewing, the diffs disappeared. 
<img width="1064" alt="08 02 2023_11 44 25_REC" src="https://user-images.githubusercontent.com/56823558/217521125-4a6443d3-fbe7-404d-9f72-6914caa4f19d.png">

**Comment by KittyJose** [comment]
This appears to be resolved.
